"""clean init

Revision ID: 5b7737d621f3
Revises: 
Create Date: 2026-04-27 02:41:56.363244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7737d621f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('unique_code', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('shift_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='employee', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token_hash', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('employee', 'admin', 'mechanic')", name='ck_users_role_valid'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'suspended')", name='ck_users_status_valid'),
    sa.CheckConstraint('char_length(trim(full_name)) > 0', name='ck_users_full_name_not_blank'),
    sa.CheckConstraint('char_length(trim(password_hash)) > 0', name='ck_users_password_hash_not_blank'),
    sa.CheckConstraint('email IS NULL OR char_length(trim(email)) > 0', name='ck_users_email_not_blank_when_present'),
    sa.CheckConstraint('rejection_reason IS NULL OR char_length(trim(rejection_reason)) > 0', name='ck_users_rejection_reason_not_blank_when_present'),
    sa.CheckConstraint('shift_number IS NULL OR char_length(trim(shift_number)) > 0', name='ck_users_shift_number_not_blank_when_present'),
    sa.CheckConstraint('unique_code IS NULL OR char_length(trim(unique_code)) > 0', name='ck_users_unique_code_not_blank_when_present'),
    sa.CheckConstraint('username IS NULL OR char_length(trim(username)) > 0', name='ck_users_username_not_blank_when_present'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_approved_by_user_id'), 'users', ['approved_by_user_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_password_reset_token_hash'), 'users', ['password_reset_token_hash'], unique=False)
    op.create_index(op.f('ix_users_rejected_by_user_id'), 'users', ['rejected_by_user_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_unique_code'), 'users', ['unique_code'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('available', 'assigned', 'in_service', 'out_of_service', name='vehicle_status'), server_default='available', nullable=False),
    sa.Column('current_mileage', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(brand)) > 0', name='ck_vehicles_brand_not_blank'),
    sa.CheckConstraint('char_length(trim(license_plate)) > 0', name='ck_vehicles_license_plate_not_blank'),
    sa.CheckConstraint('char_length(trim(model)) > 0', name='ck_vehicles_model_not_blank'),
    sa.CheckConstraint('current_mileage >= 0', name='ck_vehicles_current_mileage_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_brand'), 'vehicles', ['brand'], unique=False)
    op.create_index(op.f('ix_vehicles_created_at'), 'vehicles', ['created_at'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=True)
    op.create_index(op.f('ix_vehicles_model'), 'vehicles', ['model'], unique=False)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('contract', 'payslip', 'id_card', 'passport', 'driver_license', 'tax_number', 'bank_card', 'medical_certificate', 'other', name='document_type'), nullable=False),
    sa.Column('category', sa.Enum('company', 'personal', name='document_category'), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'archived', name='document_status'), server_default='active', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(file_name)) > 0', name='ck_documents_file_name_not_blank'),
    sa.CheckConstraint('char_length(trim(file_path)) > 0', name='ck_documents_file_path_not_blank'),
    sa.CheckConstraint('char_length(trim(mime_type)) > 0', name='ck_documents_mime_type_not_blank'),
    sa.CheckConstraint('file_size IS NULL OR file_size >= 0', name='ck_documents_file_size_non_negative'),
    sa.CheckConstraint('title IS NULL OR char_length(trim(title)) > 0', name='ck_documents_title_not_blank_when_present'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_expires_at'), 'documents', ['expires_at'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_type'), 'documents', ['type'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('employee_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('iban', sa.String(length=64), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('address IS NULL OR char_length(trim(address)) > 0', name='ck_employee_profiles_address_not_blank_when_present'),
    sa.CheckConstraint('char_length(trim(first_name)) > 0', name='ck_employee_profiles_first_name_not_blank'),
    sa.CheckConstraint('char_length(trim(last_name)) > 0', name='ck_employee_profiles_last_name_not_blank'),
    sa.CheckConstraint('department IS NULL OR char_length(trim(department)) > 0', name='ck_employee_profiles_department_not_blank_when_present'),
    sa.CheckConstraint('emergency_contact_name IS NULL OR char_length(trim(emergency_contact_name)) > 0', name='ck_emp_profiles_emerg_contact_name_not_blank'),
    sa.CheckConstraint('emergency_contact_phone IS NULL OR char_length(trim(emergency_contact_phone)) > 0', name='ck_emp_profiles_emerg_contact_phone_not_blank'),
    sa.CheckConstraint('iban IS NULL OR char_length(trim(iban)) > 0', name='ck_employee_profiles_iban_not_blank_when_present'),
    sa.CheckConstraint('phone IS NULL OR char_length(trim(phone)) > 0', name='ck_employee_profiles_phone_not_blank_when_present'),
    sa.CheckConstraint('position IS NULL OR char_length(trim(position)) > 0', name='ck_employee_profiles_position_not_blank_when_present'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_profiles_department'), 'employee_profiles', ['department'], unique=False)
    op.create_index(op.f('ix_employee_profiles_hire_date'), 'employee_profiles', ['hire_date'], unique=False)
    op.create_index(op.f('ix_employee_profiles_id'), 'employee_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_employee_profiles_phone'), 'employee_profiles', ['phone'], unique=False)
    op.create_index(op.f('ix_employee_profiles_position'), 'employee_profiles', ['position'], unique=False)
    op.create_index(op.f('ix_employee_profiles_user_id'), 'employee_profiles', ['user_id'], unique=True)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'canceled', name='leave_status'), server_default='pending', nullable=False),
    sa.Column('reviewed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'pending' AND reviewed_by_admin_id IS NULL AND reviewed_at IS NULL) OR (status IN ('approved', 'rejected') AND reviewed_by_admin_id IS NOT NULL AND reviewed_at IS NOT NULL) OR (status = 'canceled')", name='ck_leave_requests_review_fields_match_status'),
    sa.CheckConstraint('end_date >= start_date', name='ck_leave_requests_end_date_after_start_date'),
    sa.CheckConstraint('reason IS NULL OR char_length(trim(reason)) > 0', name='ck_leave_requests_reason_not_blank_if_present'),
    sa.CheckConstraint('rejection_reason IS NULL OR char_length(trim(rejection_reason)) > 0', name='ck_leave_requests_rejection_reason_not_blank_if_present'),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_created_at'), 'leave_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_leave_requests_end_date'), 'leave_requests', ['end_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.create_index(op.f('ix_leave_requests_reviewed_by_admin_id'), 'leave_requests', ['reviewed_by_admin_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_start_date'), 'leave_requests', ['start_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.create_index(op.f('ix_leave_requests_user_id'), 'leave_requests', ['user_id'], unique=False)
    op.create_table('registration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('unique_code', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('shift_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='employee', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('email_verification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verification_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('employee', 'mechanic')", name='ck_regreq_role_valid'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_regreq_status_valid'),
    sa.CheckConstraint('char_length(trim(full_name)) > 0', name='ck_regreq_full_name_not_blank'),
    sa.CheckConstraint('char_length(trim(password_hash)) > 0', name='ck_regreq_password_hash_not_blank'),
    sa.CheckConstraint('email IS NULL OR char_length(trim(email)) > 0', name='ck_regreq_email_not_blank'),
    sa.CheckConstraint('email_verification_token IS NULL OR char_length(trim(email_verification_token)) > 0', name='ck_regreq_email_verification_token_not_blank'),
    sa.CheckConstraint('rejection_reason IS NULL OR char_length(trim(rejection_reason)) > 0', name='ck_regreq_rejection_reason_not_blank'),
    sa.CheckConstraint('shift_number IS NULL OR char_length(trim(shift_number)) > 0', name='ck_regreq_shift_not_blank'),
    sa.CheckConstraint('unique_code IS NULL OR char_length(trim(unique_code)) > 0', name='ck_regreq_unique_code_not_blank'),
    sa.CheckConstraint('username IS NULL OR char_length(trim(username)) > 0', name='ck_regreq_username_not_blank'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_requests_approved_by_user_id'), 'registration_requests', ['approved_by_user_id'], unique=False)
    op.create_index(op.f('ix_registration_requests_email'), 'registration_requests', ['email'], unique=True)
    op.create_index(op.f('ix_registration_requests_email_verification_token'), 'registration_requests', ['email_verification_token'], unique=True)
    op.create_index(op.f('ix_registration_requests_full_name'), 'registration_requests', ['full_name'], unique=False)
    op.create_index(op.f('ix_registration_requests_id'), 'registration_requests', ['id'], unique=False)
    op.create_index(op.f('ix_registration_requests_rejected_by_user_id'), 'registration_requests', ['rejected_by_user_id'], unique=False)
    op.create_index(op.f('ix_registration_requests_role'), 'registration_requests', ['role'], unique=False)
    op.create_index(op.f('ix_registration_requests_status'), 'registration_requests', ['status'], unique=False)
    op.create_index(op.f('ix_registration_requests_unique_code'), 'registration_requests', ['unique_code'], unique=True)
    op.create_index(op.f('ix_registration_requests_username'), 'registration_requests', ['username'], unique=True)
    op.create_table('vehicle_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('shift_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'rejected', 'closed', name='assignment_status'), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status IN ('pending', 'active', 'rejected') AND ended_at IS NULL) OR (status = 'closed' AND ended_at IS NOT NULL)", name='ck_vehicle_assignments_status_matches_ended_at'),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name='ck_vehicle_assignments_ended_at_after_started_at'),
    sa.CheckConstraint('notes IS NULL OR char_length(trim(notes)) > 0', name='ck_vehicle_assignments_notes_not_blank_when_present'),
    sa.CheckConstraint('shift_number > 0', name='ck_vehicle_assignments_shift_number_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_assignments_created_at'), 'vehicle_assignments', ['created_at'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_ended_at'), 'vehicle_assignments', ['ended_at'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_id'), 'vehicle_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_shift_number'), 'vehicle_assignments', ['shift_number'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_started_at'), 'vehicle_assignments', ['started_at'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_status'), 'vehicle_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_user_id'), 'vehicle_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_vehicle_id'), 'vehicle_assignments', ['vehicle_id'], unique=False)
    op.create_index('ux_vehicle_assignments_active_user', 'vehicle_assignments', ['user_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'active') AND ended_at IS NULL"))
    op.create_index('ux_vehicle_assignments_active_vehicle', 'vehicle_assignments', ['vehicle_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'active') AND ended_at IS NULL"))
    op.create_table('vehicle_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('exterior', 'interior', 'damage', 'registration', name='vehicle_photo_type'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_photos_created_at'), 'vehicle_photos', ['created_at'], unique=False)
    op.create_index(op.f('ix_vehicle_photos_id'), 'vehicle_photos', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_photos_type'), 'vehicle_photos', ['type'], unique=False)
    op.create_index(op.f('ix_vehicle_photos_vehicle_id'), 'vehicle_photos', ['vehicle_id'], unique=False)
    op.create_table('vehicle_handover_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('mileage_start', sa.Integer(), nullable=True),
    sa.Column('mileage_end', sa.Integer(), nullable=True),
    sa.Column('dashboard_warnings_start', sa.Text(), nullable=True),
    sa.Column('dashboard_warnings_end', sa.Text(), nullable=True),
    sa.Column('damage_notes_start', sa.Text(), nullable=True),
    sa.Column('damage_notes_end', sa.Text(), nullable=True),
    sa.Column('notes_start', sa.Text(), nullable=True),
    sa.Column('notes_end', sa.Text(), nullable=True),
    sa.Column('has_documents', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_medkit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_extinguisher', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_warning_triangle', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_spare_wheel', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('damage_notes_end IS NULL OR char_length(trim(damage_notes_end)) > 0', name='ck_vehicle_handover_reports_damage_notes_end_not_blank'),
    sa.CheckConstraint('damage_notes_start IS NULL OR char_length(trim(damage_notes_start)) > 0', name='ck_vehicle_handover_reports_damage_notes_start_not_blank'),
    sa.CheckConstraint('dashboard_warnings_end IS NULL OR char_length(trim(dashboard_warnings_end)) > 0', name='ck_vehicle_handover_reports_dashboard_warnings_end_not_blank'),
    sa.CheckConstraint('dashboard_warnings_start IS NULL OR char_length(trim(dashboard_warnings_start)) > 0', name='ck_vehicle_handover_reports_dashboard_warnings_start_not_blank'),
    sa.CheckConstraint('mileage_end IS NULL OR mileage_end >= 0', name='ck_vehicle_handover_reports_mileage_end_non_negative'),
    sa.CheckConstraint('mileage_start IS NULL OR mileage_end IS NULL OR mileage_end >= mileage_start', name='ck_vehicle_handover_reports_mileage_end_after_start'),
    sa.CheckConstraint('mileage_start IS NULL OR mileage_start >= 0', name='ck_vehicle_handover_reports_mileage_start_non_negative'),
    sa.CheckConstraint('notes_end IS NULL OR char_length(trim(notes_end)) > 0', name='ck_vehicle_handover_reports_notes_end_not_blank'),
    sa.CheckConstraint('notes_start IS NULL OR char_length(trim(notes_start)) > 0', name='ck_vehicle_handover_reports_notes_start_not_blank'),
    sa.ForeignKeyConstraint(['assignment_id'], ['vehicle_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_handover_reports_assignment_id'), 'vehicle_handover_reports', ['assignment_id'], unique=True)
    op.create_index(op.f('ix_vehicle_handover_reports_created_at'), 'vehicle_handover_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_vehicle_handover_reports_id'), 'vehicle_handover_reports', ['id'], unique=False)
    op.create_table('vehicle_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('reported_by_user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_mechanic_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='vehicle_issue_priority'), server_default='medium', nullable=False),
    sa.Column('need_service_in_km', sa.Integer(), nullable=True),
    sa.Column('need_brakes', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('need_tires', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('need_oil', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dashboard_checks', sa.Text(), nullable=True),
    sa.Column('other_problems', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'scheduled', 'in_progress', 'resolved', 'canceled', name='vehicle_issue_status'), server_default='open', nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_location', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Integer(), nullable=True),
    sa.Column('final_cost', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status != 'scheduled' OR scheduled_for IS NOT NULL", name='ck_vehicle_issues_scheduled_requires_datetime'),
    sa.CheckConstraint('dashboard_checks IS NULL OR char_length(trim(dashboard_checks)) > 0', name='ck_vehicle_issues_dashboard_checks_not_blank_if_present'),
    sa.CheckConstraint('estimated_cost IS NULL OR estimated_cost >= 0', name='ck_vehicle_issues_estimated_cost_non_negative'),
    sa.CheckConstraint('final_cost IS NULL OR final_cost >= 0', name='ck_vehicle_issues_final_cost_non_negative'),
    sa.CheckConstraint('need_service_in_km IS NULL OR need_service_in_km >= 0', name='ck_vehicle_issues_need_service_in_km_non_negative'),
    sa.CheckConstraint('other_problems IS NULL OR char_length(trim(other_problems)) > 0', name='ck_vehicle_issues_other_problems_not_blank_if_present'),
    sa.CheckConstraint('resolution_notes IS NULL OR char_length(trim(resolution_notes)) > 0', name='ck_vehicle_issues_resolution_notes_not_blank_if_present'),
    sa.CheckConstraint('scheduled_location IS NULL OR char_length(trim(scheduled_location)) > 0', name='ck_vehicle_issues_scheduled_location_not_blank_if_present'),
    sa.CheckConstraint('scheduled_location IS NULL OR scheduled_for IS NOT NULL', name='ck_vehicle_issues_scheduled_location_requires_datetime'),
    sa.CheckConstraint('started_at IS NULL OR resolved_at IS NULL OR resolved_at >= started_at', name='ck_vehicle_issues_resolved_at_after_started_at'),
    sa.ForeignKeyConstraint(['assigned_mechanic_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assignment_id'], ['vehicle_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_issues_assigned_mechanic_id'), 'vehicle_issues', ['assigned_mechanic_id'], unique=False)
    op.create_index(op.f('ix_vehicle_issues_assignment_id'), 'vehicle_issues', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_vehicle_issues_created_at'), 'vehicle_issues', ['created_at'], unique=False)
    op.create_index(op.f('ix_vehicle_issues_id'), 'vehicle_issues', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_issues_priority'), 'vehicle_issues', ['priority'], unique=False)
    op.create_index(op.f('ix_vehicle_issues_reported_by_user_id'), 'vehicle_issues', ['reported_by_user_id'], unique=False)
    op.create_index(op.f('ix_vehicle_issues_resolved_at'), 'vehicle_issues', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_vehicle_issues_scheduled_for'), 'vehicle_issues', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_vehicle_issues_started_at'), 'vehicle_issues', ['started_at'], unique=False)
    op.create_index(op.f('ix_vehicle_issues_status'), 'vehicle_issues', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_issues_vehicle_id'), 'vehicle_issues', ['vehicle_id'], unique=False)
    op.create_table('vehicle_issue_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['vehicle_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_issue_photos_id'), 'vehicle_issue_photos', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_issue_photos_issue_id'), 'vehicle_issue_photos', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_issue_photos_issue_id'), table_name='vehicle_issue_photos')
    op.drop_index(op.f('ix_vehicle_issue_photos_id'), table_name='vehicle_issue_photos')
    op.drop_table('vehicle_issue_photos')
    op.drop_index(op.f('ix_vehicle_issues_vehicle_id'), table_name='vehicle_issues')
    op.drop_index(op.f('ix_vehicle_issues_status'), table_name='vehicle_issues')
    op.drop_index(op.f('ix_vehicle_issues_started_at'), table_name='vehicle_issues')
    op.drop_index(op.f('ix_vehicle_issues_scheduled_for'), table_name='vehicle_issues')
    op.drop_index(op.f('ix_vehicle_issues_resolved_at'), table_name='vehicle_issues')
    op.drop_index(op.f('ix_vehicle_issues_reported_by_user_id'), table_name='vehicle_issues')
    op.drop_index(op.f('ix_vehicle_issues_priority'), table_name='vehicle_issues')
    op.drop_index(op.f('ix_vehicle_issues_id'), table_name='vehicle_issues')
    op.drop_index(op.f('ix_vehicle_issues_created_at'), table_name='vehicle_issues')
    op.drop_index(op.f('ix_vehicle_issues_assignment_id'), table_name='vehicle_issues')
    op.drop_index(op.f('ix_vehicle_issues_assigned_mechanic_id'), table_name='vehicle_issues')
    op.drop_table('vehicle_issues')
    op.drop_index(op.f('ix_vehicle_handover_reports_id'), table_name='vehicle_handover_reports')
    op.drop_index(op.f('ix_vehicle_handover_reports_created_at'), table_name='vehicle_handover_reports')
    op.drop_index(op.f('ix_vehicle_handover_reports_assignment_id'), table_name='vehicle_handover_reports')
    op.drop_table('vehicle_handover_reports')
    op.drop_index(op.f('ix_vehicle_photos_vehicle_id'), table_name='vehicle_photos')
    op.drop_index(op.f('ix_vehicle_photos_type'), table_name='vehicle_photos')
    op.drop_index(op.f('ix_vehicle_photos_id'), table_name='vehicle_photos')
    op.drop_index(op.f('ix_vehicle_photos_created_at'), table_name='vehicle_photos')
    op.drop_table('vehicle_photos')
    op.drop_index('ux_vehicle_assignments_active_vehicle', table_name='vehicle_assignments', postgresql_where=sa.text("status IN ('pending', 'active') AND ended_at IS NULL"))
    op.drop_index('ux_vehicle_assignments_active_user', table_name='vehicle_assignments', postgresql_where=sa.text("status IN ('pending', 'active') AND ended_at IS NULL"))
    op.drop_index(op.f('ix_vehicle_assignments_vehicle_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_user_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_status'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_started_at'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_shift_number'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_ended_at'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_created_at'), table_name='vehicle_assignments')
    op.drop_table('vehicle_assignments')
    op.drop_index(op.f('ix_registration_requests_username'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_unique_code'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_status'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_role'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_rejected_by_user_id'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_id'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_full_name'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_email_verification_token'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_email'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_approved_by_user_id'), table_name='registration_requests')
    op.drop_table('registration_requests')
    op.drop_index(op.f('ix_leave_requests_user_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_start_date'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_reviewed_by_admin_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_end_date'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_created_at'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_employee_profiles_user_id'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_position'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_phone'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_id'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_hire_date'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_department'), table_name='employee_profiles')
    op.drop_table('employee_profiles')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_expires_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_model'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_license_plate'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_created_at'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_brand'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_unique_code'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_rejected_by_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_password_reset_token_hash'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_approved_by_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
