"""add registration_requests table

Revision ID: 942cc1992a78
Revises: 6f1bda129984
Create Date: 2026-04-21 23:33:27.960227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942cc1992a78'
down_revision: Union[str, Sequence[str], None] = '6f1bda129984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('unique_code', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('shift_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='employee', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('employee', 'mechanic')", name='ck_regreq_role_valid'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_regreq_status_valid'),
    sa.CheckConstraint('char_length(trim(full_name)) > 0', name='ck_regreq_full_name_not_blank'),
    sa.CheckConstraint('char_length(trim(password_hash)) > 0', name='ck_regreq_password_hash_not_blank'),
    sa.CheckConstraint('email IS NULL OR char_length(trim(email)) > 0', name='ck_regreq_email_not_blank'),
    sa.CheckConstraint('rejection_reason IS NULL OR char_length(trim(rejection_reason)) > 0', name='ck_regreq_rejection_reason_not_blank'),
    sa.CheckConstraint('shift_number IS NULL OR char_length(trim(shift_number)) > 0', name='ck_regreq_shift_not_blank'),
    sa.CheckConstraint('unique_code IS NULL OR char_length(trim(unique_code)) > 0', name='ck_regreq_unique_code_not_blank'),
    sa.CheckConstraint('username IS NULL OR char_length(trim(username)) > 0', name='ck_regreq_username_not_blank'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_requests_approved_by_user_id'), 'registration_requests', ['approved_by_user_id'], unique=False)
    op.create_index(op.f('ix_registration_requests_email'), 'registration_requests', ['email'], unique=True)
    op.create_index(op.f('ix_registration_requests_full_name'), 'registration_requests', ['full_name'], unique=False)
    op.create_index(op.f('ix_registration_requests_id'), 'registration_requests', ['id'], unique=False)
    op.create_index(op.f('ix_registration_requests_rejected_by_user_id'), 'registration_requests', ['rejected_by_user_id'], unique=False)
    op.create_index(op.f('ix_registration_requests_role'), 'registration_requests', ['role'], unique=False)
    op.create_index(op.f('ix_registration_requests_status'), 'registration_requests', ['status'], unique=False)
    op.create_index(op.f('ix_registration_requests_unique_code'), 'registration_requests', ['unique_code'], unique=True)
    op.create_index(op.f('ix_registration_requests_username'), 'registration_requests', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_requests_username'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_unique_code'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_status'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_role'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_rejected_by_user_id'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_id'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_full_name'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_email'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_approved_by_user_id'), table_name='registration_requests')
    op.drop_table('registration_requests')
    # ### end Alembic commands ###
